version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27018:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
    environment:
    - API_KEY=${API_KEY}
    - API_SECRET=${API_SECRET}
    - ACCESS_TOKEN=${ACCESS_TOKEN}
    - SECRET_ACCESS_TOKEN=${SECRET_ACCESS_TOKEN}

  postgresdb:
    image: postgres
    ports:
      - "5556:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nytimes

  etl_job:
    build: etl_job/
    volumes:
      - ./etl_job/:/app 
    depends_on: 
      - mongodb
      - postgresdb
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
  telegram_bot:
    build: telegram_bot/
    volumes:
      - ./telegram_bot/:/app 
    depends_on: 
      - postgresdb
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TOKEN_TELEGRAM=${TOKEN_TELEGRAM}

  tweet_eraser:
    build: tweet_eraser/
    volumes:
      - ./tweet_eraser/:/app 
    depends_on: 
      - mongodb
      - postgresdb
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  
